jQuery(document).ready(function($) { 
	$(".login_button").click(function(){
		$.ajax({
            url:'re/login.php?request=login',
            dataType:"json",
            type:"post",
            aysnc:false,
            data:{
                username:$(".username").val(),
                password:$(".password").val()
            },
            success:function(result){
                console.log(result)
                $(".login_button").hide()
            }
          })
	})
	$(".register_button").click(function(){
		$.ajax({
            url:'re/login.php?request=register',
            dataType:"json",
            type:"post",
            aysnc:false,
            data:{
                username:$(".usernameg").val(),
                password:$(".passwordg").val(),
                tel:$(".telg").val()

            },
            success:function(result){
                console.log(result)
            }
          })
	})
})